sudo: required
services:
  - docker

language: java
jdk: oraclejdk8

branches:
  only:
    - master

before_install:
  - docker version
  - docker info

script:
  - mvn clean verify -f alma-server/pom.xml -e

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker images
  - docker push arayabegaudeau/alma-server:latest


deploy:
  provider: releases
  api_key: 0f39394cb78290e5b26fd9c42b4225bf2a82f931
  file: "alma-server-1.0.0-SNAPSHOT.jar"
  skip_cleanup: true
  on:
    repo: Araya-Begaudeau/alma-m2-2017
    tags: true
